name: Deploy Varefer_Bot1
on: [push]
jobs:
  
  build:
    name: Deploy Varefer_Bot1
    runs-on: self-hosted
    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.HOSTIP1_VAREFER }}
        username: ${{ secrets.HOST_USERNAME }}
        key: ${{ secrets.RUNNER_VAREFERKEY }}
        port: ${{ secrets.HOST_PORT }}
        script: |
          cd Varefer
          git pull origin main
          sudo docker build -t varefer:latest .
          sudo docker-compose down
          sudo docker-compose up -d
          sudo docker ps -a
          sudo docker logs bot_1
          sudo docker system prune -a
          sudo docker images
          
